### ISSUE TITLE
How to get subview within an item?

### ISSUE THREAD

**Issue by plastus** [gotev/recycler-adapter#1]
Hello,

I was wondering what is the correct way of obtaining a view within one of the RecyclerView items? The very first item I am adding to my adapter is a calendar view. I need to set some listeners to the calendar view but I can't figure out a way to obtain the view.

I have tried recyclerView.findViewById and findViewHolderByPosition but they always return null. Any suggestion would be greatly appreciated!

**Comment by gotev** [comment]
So you have an item with a calendar in it right? You can get a reference to the view only inside the view holder of the view model. Listeners are setup in the view holder too. I suggest you to check the example provided in the readme in which I show how to handle click events. You should be able to get the point from there ;) Remember that you shouldn't need to reference a view inside a particular view holder from outside the recyclerview, otherwise I suggest you to revisit your layout architecture.

**Comment by plastus** [comment]
Thank you for your quick response! I am new to Android development so I reviewed the readme and examples again. I think I'm starting to get a hang of it. :) I was able to get my calendar working by doing everything in the view holder. I am going to play around with creating items that have buttons/text fields inside them. I should be able to do this and eventually pull out all of the values of buttons or text fields within items if I have some sort of submit feature?

Thank you again!
